name = "gemini-loadbalance-rotator-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"

compatibility_flags = ["nodejs_compat"]

# --- KV Namespaces ---
kv_namespaces = [
  { binding = "GEMINI_CLI_LOADBALANCE", id = "..." }
]


#[vars]
# NOTE: Secrets (OAuth JSON blobs) were removed from this file.
# Store per-credential JSON files in the repository's "oauth creds/" directory (this directory is gitignored),
# then push them to Cloudflare using `wrangler secret put` or the included helper script:
#   npm run push-secrets    # dry-run
#   npm run push-secrets:run  # actually push
# Do NOT keep OAuth JSON blobs or `.dev.vars` in `wrangler.toml` or in the git history.


# --- Local Development Configuration ---
# This section configures local development with Docker and miniflare
[dev]
ip = "0.0.0.0"          # Bind to all interfaces for Docker access
port = 8787             # Port for local development server
# Note: --persist-to flag in Docker handles storage location

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
